# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from autoweaver.motion_policy._proto import motion_pb2 as motion__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in motion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MotionServiceStub(object):
    """motion-runtime 0.7.0 — thin translation layer.

    Leaves read/write by field name; runtime looks up (slave_position, offset,
    type) in the YAML contract and does the actual PDO byte I/O.

    Core stance: runtime understands no business semantics; leaves know nothing
    about byte layouts. The three parties (leaf / runtime / external controller
    code) couple only through "the set of field names"; the YAML contract is
    the single source of truth.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteField = channel.unary_unary(
                '/motion.MotionService/WriteField',
                request_serializer=motion__pb2.WriteFieldRequest.SerializeToString,
                response_deserializer=motion__pb2.WriteFieldResponse.FromString,
                _registered_method=True)
        self.WriteFields = channel.unary_unary(
                '/motion.MotionService/WriteFields',
                request_serializer=motion__pb2.WriteFieldsRequest.SerializeToString,
                response_deserializer=motion__pb2.WriteFieldsResponse.FromString,
                _registered_method=True)
        self.ReadField = channel.unary_unary(
                '/motion.MotionService/ReadField',
                request_serializer=motion__pb2.ReadFieldRequest.SerializeToString,
                response_deserializer=motion__pb2.ReadFieldResponse.FromString,
                _registered_method=True)


class MotionServiceServicer(object):
    """motion-runtime 0.7.0 — thin translation layer.

    Leaves read/write by field name; runtime looks up (slave_position, offset,
    type) in the YAML contract and does the actual PDO byte I/O.

    Core stance: runtime understands no business semantics; leaves know nothing
    about byte layouts. The three parties (leaf / runtime / external controller
    code) couple only through "the set of field names"; the YAML contract is
    the single source of truth.

    """

    def WriteField(self, request, context):
        """Encode the value and write it into the slave's RxPDO output buffer.
        It goes out on the next EtherCAT cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFields(self, request, context):
        """Atomic multi-field write. Runtime stages all fields, validates the
        whole set, then commits them in one shared-memory snapshot — the
        external controller (SPEL+) never sees a torn write where some
        fields are new and some still hold previous values.

        Semantics: all-or-nothing. If any field is unknown / type-mismatched
        / rejected, ok=false and nothing is committed; failed_field names
        the first offender.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadField(self, request, context):
        """Decode a field from the slave's most-recent TxPDO input buffer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteField': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteField,
                    request_deserializer=motion__pb2.WriteFieldRequest.FromString,
                    response_serializer=motion__pb2.WriteFieldResponse.SerializeToString,
            ),
            'WriteFields': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFields,
                    request_deserializer=motion__pb2.WriteFieldsRequest.FromString,
                    response_serializer=motion__pb2.WriteFieldsResponse.SerializeToString,
            ),
            'ReadField': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadField,
                    request_deserializer=motion__pb2.ReadFieldRequest.FromString,
                    response_serializer=motion__pb2.ReadFieldResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'motion.MotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('motion.MotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionService(object):
    """motion-runtime 0.7.0 — thin translation layer.

    Leaves read/write by field name; runtime looks up (slave_position, offset,
    type) in the YAML contract and does the actual PDO byte I/O.

    Core stance: runtime understands no business semantics; leaves know nothing
    about byte layouts. The three parties (leaf / runtime / external controller
    code) couple only through "the set of field names"; the YAML contract is
    the single source of truth.

    """

    @staticmethod
    def WriteField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/WriteField',
            motion__pb2.WriteFieldRequest.SerializeToString,
            motion__pb2.WriteFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/WriteFields',
            motion__pb2.WriteFieldsRequest.SerializeToString,
            motion__pb2.WriteFieldsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/ReadField',
            motion__pb2.ReadFieldRequest.SerializeToString,
            motion__pb2.ReadFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
