# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from autoweaver.motion_policy._proto import motion_pb2 as motion__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in motion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MotionServiceStub(object):
    """motion-runtime 0.8.0 — goal service layer.

    Leaves submit business-level goals ("do a LINEAR move to (x, y, z, u) at
    speed N"); runtime owns the field-level write/trigger/done handshake plus
    EtherCAT byte translation. Field-level RPCs are intentionally not exposed:
    the protocol contract between Python and Rust is the goal vocabulary, not
    the wire layout.

    Atomicity: runtime stages target fields in a shadow PDO buffer and commits
    them as one snapshot before raising the trigger edge — the external
    controller never sees a torn write.

    Status: submit is non-blocking. The runtime starts the handshake, returns
    immediately, and the caller polls Read*Status for done/busy/error. A BT
    leaf's on_running ticks once per BT tick and reads status — submit must
    not block the tick.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitScaraGoal = channel.unary_unary(
                '/motion.MotionService/SubmitScaraGoal',
                request_serializer=motion__pb2.ScaraGoal.SerializeToString,
                response_deserializer=motion__pb2.GoalResponse.FromString,
                _registered_method=True)
        self.ReadScaraStatus = channel.unary_unary(
                '/motion.MotionService/ReadScaraStatus',
                request_serializer=motion__pb2.StatusRequest.SerializeToString,
                response_deserializer=motion__pb2.ScaraStatusResponse.FromString,
                _registered_method=True)
        self.SubmitArm6Goal = channel.unary_unary(
                '/motion.MotionService/SubmitArm6Goal',
                request_serializer=motion__pb2.Arm6Goal.SerializeToString,
                response_deserializer=motion__pb2.GoalResponse.FromString,
                _registered_method=True)
        self.ReadArm6Status = channel.unary_unary(
                '/motion.MotionService/ReadArm6Status',
                request_serializer=motion__pb2.StatusRequest.SerializeToString,
                response_deserializer=motion__pb2.Arm6StatusResponse.FromString,
                _registered_method=True)


class MotionServiceServicer(object):
    """motion-runtime 0.8.0 — goal service layer.

    Leaves submit business-level goals ("do a LINEAR move to (x, y, z, u) at
    speed N"); runtime owns the field-level write/trigger/done handshake plus
    EtherCAT byte translation. Field-level RPCs are intentionally not exposed:
    the protocol contract between Python and Rust is the goal vocabulary, not
    the wire layout.

    Atomicity: runtime stages target fields in a shadow PDO buffer and commits
    them as one snapshot before raising the trigger edge — the external
    controller never sees a torn write.

    Status: submit is non-blocking. The runtime starts the handshake, returns
    immediately, and the caller polls Read*Status for done/busy/error. A BT
    leaf's on_running ticks once per BT tick and reads status — submit must
    not block the tick.

    """

    def SubmitScaraGoal(self, request, context):
        """SCARA (4-DOF): x, y, z, u — used for Epson LS6 today.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadScaraStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitArm6Goal(self, request, context):
        """Generic 6-DOF arm (x, y, z, rx, ry, rz). Reserved for the first
        EtherCAT-fronted 6-DOF arm we integrate; message shape may evolve when
        a concrete device drives the requirements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArm6Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitScaraGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitScaraGoal,
                    request_deserializer=motion__pb2.ScaraGoal.FromString,
                    response_serializer=motion__pb2.GoalResponse.SerializeToString,
            ),
            'ReadScaraStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadScaraStatus,
                    request_deserializer=motion__pb2.StatusRequest.FromString,
                    response_serializer=motion__pb2.ScaraStatusResponse.SerializeToString,
            ),
            'SubmitArm6Goal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitArm6Goal,
                    request_deserializer=motion__pb2.Arm6Goal.FromString,
                    response_serializer=motion__pb2.GoalResponse.SerializeToString,
            ),
            'ReadArm6Status': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArm6Status,
                    request_deserializer=motion__pb2.StatusRequest.FromString,
                    response_serializer=motion__pb2.Arm6StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'motion.MotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('motion.MotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionService(object):
    """motion-runtime 0.8.0 — goal service layer.

    Leaves submit business-level goals ("do a LINEAR move to (x, y, z, u) at
    speed N"); runtime owns the field-level write/trigger/done handshake plus
    EtherCAT byte translation. Field-level RPCs are intentionally not exposed:
    the protocol contract between Python and Rust is the goal vocabulary, not
    the wire layout.

    Atomicity: runtime stages target fields in a shadow PDO buffer and commits
    them as one snapshot before raising the trigger edge — the external
    controller never sees a torn write.

    Status: submit is non-blocking. The runtime starts the handshake, returns
    immediately, and the caller polls Read*Status for done/busy/error. A BT
    leaf's on_running ticks once per BT tick and reads status — submit must
    not block the tick.

    """

    @staticmethod
    def SubmitScaraGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/SubmitScaraGoal',
            motion__pb2.ScaraGoal.SerializeToString,
            motion__pb2.GoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadScaraStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/ReadScaraStatus',
            motion__pb2.StatusRequest.SerializeToString,
            motion__pb2.ScaraStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitArm6Goal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/SubmitArm6Goal',
            motion__pb2.Arm6Goal.SerializeToString,
            motion__pb2.GoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadArm6Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/ReadArm6Status',
            motion__pb2.StatusRequest.SerializeToString,
            motion__pb2.Arm6StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
