#!/usr/bin/env bash
#
# Install IgH EtherCAT Master (generic mode) on Ubuntu with RT kernel.
#
# Usage:
#   sudo ./install-igh-ethercat.sh <NIC_INTERFACE>
#
# Example:
#   sudo ./install-igh-ethercat.sh eno2
#
# Prerequisites:
#   - Ubuntu 22.04/24.04 with linux-headers installed for the running kernel
#   - Root privileges
#
# What this script does:
#   1. Installs build dependencies
#   2. Clones IgH EtherCAT Master (stable-1.5)
#   3. Compiles with generic driver (works with any NIC, including Intel I226-V / igc)
#   4. Installs kernel modules, CLI tool, libraries, and init script
#   5. Configures /etc/sysconfig/ethercat with the specified NIC's MAC address
#   6. Creates udev rule for /dev/EtherCAT0 access
#   7. Starts the ethercat service
#
set -euo pipefail

# --- Argument parsing ---
if [ $# -lt 1 ]; then
    echo "Usage: sudo $0 <NIC_INTERFACE>"
    echo "Example: sudo $0 eno2"
    exit 1
fi

NIC="$1"

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: must run as root (sudo)"
    exit 1
fi

# Verify the NIC exists
if ! ip link show "$NIC" &>/dev/null; then
    echo "Error: network interface '$NIC' not found"
    echo "Available interfaces:"
    ip -br link show
    exit 1
fi

# Verify kernel headers are available
KDIR="/lib/modules/$(uname -r)/build"
if [ ! -d "$KDIR" ]; then
    echo "Error: kernel headers not found at $KDIR"
    echo "Install them with: sudo apt-get install linux-headers-$(uname -r)"
    exit 1
fi

MAC=$(ip link show "$NIC" | awk '/ether/ {print $2}')
echo "==> NIC: $NIC  MAC: $MAC  Kernel: $(uname -r)"

# --- Step 1: Install build dependencies ---
echo "==> Installing build dependencies..."
apt-get update -qq
apt-get install -y -qq build-essential autoconf automake libtool pkg-config git

# --- Step 2: Clone IgH source ---
BUILD_DIR="/tmp/igh-ethercat-build"
rm -rf "$BUILD_DIR"
echo "==> Cloning IgH EtherCAT Master (stable-1.5)..."
git clone --depth 1 --branch stable-1.5 https://gitlab.com/etherlab.org/ethercat.git "$BUILD_DIR"
cd "$BUILD_DIR"

# --- Step 3: Build ---
echo "==> Bootstrapping autotools..."
./bootstrap

echo "==> Configuring (generic driver only, EoE disabled)..."
./configure \
    --prefix=/usr/local \
    --sysconfdir=/etc \
    --enable-generic \
    --disable-8139too \
    --disable-e100 \
    --disable-e1000 \
    --disable-e1000e \
    --disable-igb \
    --disable-r8169 \
    --disable-eoe \
    --enable-sii-assign \
    --enable-hrtimer \
    --with-linux-dir="$KDIR"

echo "==> Compiling..."
make -j"$(nproc)"
make modules

# --- Step 4: Install ---
echo "==> Installing..."
make install
make modules_install
depmod -a
ldconfig

# --- Step 5: Configure ---
# stable-1.5 has two config paths: init.d reads /etc/sysconfig/ethercat,
# ethercatctl (systemd) reads /usr/local/etc/ethercat.conf. Write both.
ETHERCAT_CONF="# IgH EtherCAT Master configuration
# Generated by install-igh-ethercat.sh on $(date -Iseconds)
# NIC: $NIC
MASTER0_DEVICE=\"$MAC\"
DEVICE_MODULES=\"generic\""

echo "==> Writing EtherCAT config files..."
mkdir -p /etc/sysconfig
echo "$ETHERCAT_CONF" > /etc/sysconfig/ethercat
mkdir -p /usr/local/etc
echo "$ETHERCAT_CONF" > /usr/local/etc/ethercat.conf

# --- Step 6: udev rule ---
echo "==> Creating udev rule for /dev/EtherCAT*..."
cat > /etc/udev/rules.d/99-ethercat.rules << 'EOF'
KERNEL=="EtherCAT[0-9]*", MODE="0666"
EOF
udevadm control --reload-rules

# --- Step 7: Start service ---
echo "==> Bringing up NIC and starting ethercat service..."
ip link set "$NIC" up 2>/dev/null || true
if systemctl list-unit-files ethercat.service &>/dev/null; then
    systemctl daemon-reload
    systemctl enable ethercat
    systemctl restart ethercat
else
    /etc/init.d/ethercat start
fi
sleep 2

# --- Verify ---
echo ""
echo "=== Verification ==="
if ethercat master &>/dev/null; then
    SLAVES=$(ethercat slaves 2>/dev/null | wc -l)
    echo "IgH EtherCAT Master is running."
    echo "Detected $SLAVES slave(s)."
    ethercat slaves 2>/dev/null
else
    echo "WARNING: ethercat master command failed. Check dmesg for details."
    dmesg | grep -i ethercat | tail -10
fi

echo ""
echo "Done. To check status:  ethercat master"
echo "         list slaves:   ethercat slaves"
echo "         slave details: ethercat slaves -v"
echo "         PDO mapping:   ethercat pdos"

# Cleanup
rm -rf "$BUILD_DIR"
